name: barcode_app
description: "Barcode App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.0
  cached_network_image: ^3.2.3
  stacked: ^3.4.0
  functional_widget_annotation: ^0.10.0
  get_it: ^7.7.0
  injectable: ^2.1.2
  barcode_scan2: ^4.3.3
  dio: ^5.5.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.1.6
  functional_widget: ^0.10.1
  build_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/strings/
